# Site settings
title:          Tim Williams
description:    "Humble data fabulist"
baseurl:        ""
url:            "https://timajwilliams.github.io"

# Google Analytics
google_analytics: G-DPXHVXG0EJ

# Author
author:
  name:         Tim Williams
  url:          https://www.timajwilliams.com
  email:        tim@timajwilliams.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji 
  - jekyll-mermaid

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
